---
output: pdf_document
header-includes:
  - \usepackage{float}
  - \newcommand{\beginsupplement}{\setcounter{figure}{0} \renewcommand{\thefigure}{S\arabic{figure}}}
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      fig.align = 'center',
                      fig.pos = 'H')
```

\beginsupplement

```{r example-purity,fig.height=6,fig.cap='Examples of low and high purity 0.01 amu spectral bins. Both bins were taken from the human urine positive ionisation mode example matrix. The upper half of the graph shows the kernal density estimate distribution of the abundance spectrum below.' }
loadd(example_low_purity_bin_plot,
      example_high_purity_bin_plot)

example_low_purity_bin_plot - example_high_purity_bin_plot + 
  plot_layout(ncol = 1)
```

```{r example-centrality,fig.height=6,fig.cap='Examples of low and high centrality, 0.01 amu spectral bins. a) Bin 94.05 \\textit{m/z} was taken from the \\textit{B. distachyon} leaf positive ionisation mode example matrix. b) Bin 61.04 \\textit{m/z} was taken from the human urine positive ionisation mode example matrix.'}
loadd(example_low_centrality_bin_plot,
      example_high_centrality_bin_plot)

example_low_centrality_bin_plot - example_high_centrality_bin_plot + 
  plot_layout(ncol = 1)
```

```{r deviation,fig.cap="Deviations in \\textit{m/z} for an example peak between the scans of a single sample and across replicate injections. \\textit{m/z} deviations taken from the base peak at 133.01416 \\textit{m/z} in 10 replicate injections of the \\textit{B. distachyon} leaf negative ionisation mode example matrix. The \\textit{m/z} deviations between the scans of the single sample were taken from the detected 'plug' flow of the first replicate"}
loadd(malate_single_sample_deviation_plot,
      malate_sample_deviation_plot)

malate_single_sample_deviation_plot + malate_sample_deviation_plot
```

```{r split,fig.width=4,fig.cap='An example of peak "splitting" at 0.001 amu bin width. a) A kernal density distribution plot of the negative ionisation mode bin at 215.09 \\textit{m/z}, averaged across the 10 replicate injections of the example urine sample matrix. The red lines denote the 0.001 amu bin width boundaries. The grey shaded areas denote the 0.001 amu adjacent bins that are plotted in (b). b) A scatter plot of the abundances for the adjacent 0.001 amu bins 215.092 and 215.093 in negative ionisation mode for the 10 technical injections of the example urine sample matrix. The pearsons correlation coefficient between the bins is shown along with its \\textit{p}-value.'}
loadd(example_dp3_split_bin_plot,
      example_dp3_adjacent_scatter_plot)

{example_dp3_split_bin_plot + 
    labs(title = 'a)')} +
  {example_dp3_adjacent_scatter_plot +
      labs(title = 'b)')} +
  plot_layout(ncol = 1,heights = c(1,2))
```

```{r binneR-performance, fig.width=5,fig.height=6,fig.cap = 'Performance benchmarking results of processing time and peak memory usage for the binneR R package. The raw data files from the 10 replicate injections of the \\textit{B. distachyon} leaf sample matrix were used. The data files were duplicated 10 and 100 times for the 100 and 1000 file tests respectively.'}
readd(performance_plot)
```
