---
output: pdf_document
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
  - \newcommand{\beginsupplement}{\setcounter{table}{1}  \renewcommand{\thetable}{S\arabic{table}}}
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE)
```

\beginsupplement

```{r matrix-overview}
loadd(matrix_features_overview)
matrix_features_overview %>%
  spread(Mode,N) %>%
  mutate(amu = format(amu,scientific = FALSE)) %>%
  select(amu,everything()) %>%
  arrange(amu) %>%
  rename(`Bin width (amu)` = amu,`Biological matrix` = Matrix,`Negative mode` = n,`Positive mode` = p) %>%
  kable(align = c('r','l','r','r'),
        format = 'latex',
        booktabs = TRUE,
        linesep = c(rep('',3),'\\addlinespace'),
        caption = 'Total numbers of bins at incremental amu bin width detected across the 10 replicate injections of each of the example biological sample matrices for each ionisation modes.') %>%
  kable_styling(position = 'center') %>%
  collapse_rows(columns = 1,valign = 'middle',latex_hline = 'major') %>%
  add_header_above(c(' ' = 2,'Total number of bins' = 2))
```

```{r missing-data}
loadd(matrix_missing_data)
matrix_missing_data %>%
  select(amu,Matrix,Mode,Percent) %>%
  mutate(Percent = signif(Percent,3)) %>%
  spread(Mode,Percent) %>%
  mutate(amu = format(amu,scientific = FALSE)) %>%
  arrange(amu) %>%
  rename(`Bin width (amu)` = amu,`Biological matrix` = Matrix,`Negative mode` = n,`Positive mode` = p) %>%
  kable(align = c('r','l','r','r'),
        format = 'latex',
        booktabs = TRUE,
        linesep = c(rep('',3),'\\addlinespace'),
        caption = 'The percentage of missing data detected at incremental amu bin width across the 10 replicate injections of each of the example biological sample matrices for each ionisation mode.') %>%
  kable_styling(position = 'center') %>%
  collapse_rows(columns = 1,valign = 'middle',latex_hline = 'major') %>%
  add_header_above(c(' ' = 2,'Missing data (%)' = 2))
```
